version: '3.3'
services:
  frontend-dev:
    container_name: frontend-dev
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true 
    depends_on:
      - server-dev

  server-dev:
    container_name: server-dev
    restart: unless-stopped
    build: 
      context: ./server
      dockerfile: ./Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./server/src:/app/src